### ISSUE TITLE
GPT4Free

### ISSUE THREAD

**Issue by ilnarildarovuch** [Vauth/duckgpt#3]
If create an PULL request to the GPT4Free, you can get respect from others. (All other variants not working from now)

**Comment by Vauth** [comment]
I see, I have no info about that. can you do it.

**Comment by ilnarildarovuch** [comment]
J4f. Like that: https://github.com/xtekky/gpt4free

**Comment by Vauth** [comment]
> J4f. Like that: https://github.com/xtekky/gpt4free

They are already using duckchat api.

**Comment by ilnarildarovuch** [comment]
Oh, then sorry
